openapi: 3.1.0
info:
  title: Notion Page Creator
  version: 1.0.0
  description: API to create pages in Notion via a proxy server
servers:
  - url: https://your-proxy-server.com
paths:
  /create-notion-page:
    post:
      operationId: createNotionPage
      summary: Create a new page in Notion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the Notion page
                content:
                  type: string
                  description: Content of the Notion page
              required:
                - title
                - content
      responses:
        '200':
          description: Page created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
        '500':
          description: Error creating page
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: object
components: {}
